# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
